"""create_dim_taxonomy_tables

Revision ID: 8a74f5fad03b
Revises: 
Create Date: 2026-10-07 14:35:54.802597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a74f5fad03b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_dim_brand_code'), 'dim_brand', ['code'], unique=True)
    op.create_index(op.f('ix_dim_brand_id'), 'dim_brand', ['id'], unique=False)
    op.create_table('dim_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dim_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_dim_category_code'), 'dim_category', ['code'], unique=True)
    op.create_index(op.f('ix_dim_category_id'), 'dim_category', ['id'], unique=False)
    op.create_table('dim_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('multiplier_weight', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_condition_code'), 'dim_condition', ['code'], unique=True)
    op.create_index(op.f('ix_dim_condition_id'), 'dim_condition', ['id'], unique=False)
    op.create_table('dim_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_dim_source_code'), 'dim_source', ['code'], unique=True)
    op.create_index(op.f('ix_dim_source_id'), 'dim_source', ['id'], unique=False)
    op.create_table('dim_product_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['dim_brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_product_family_id'), 'dim_product_family', ['id'], unique=False)
    op.create_table('dim_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('model_code', sa.String(length=100), nullable=True),
    sa.Column('base_specs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['dim_brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['dim_product_family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_product_id'), 'dim_product', ['id'], unique=False)
    op.create_index(op.f('ix_dim_product_slug'), 'dim_product', ['slug'], unique=True)
    op.create_table('dim_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('canonical_id', sa.String(length=200), nullable=False),
    sa.Column('variant_specs', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_variant_canonical_id'), 'dim_variant', ['canonical_id'], unique=True)
    op.create_index(op.f('ix_dim_variant_id'), 'dim_variant', ['id'], unique=False)
    op.create_index(op.f('ix_dim_variant_sku'), 'dim_variant', ['sku'], unique=True)
    op.create_table('dim_market_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('target_price_ref', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['dim_condition.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['dim_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_market_segment_canonical_key'), 'dim_market_segment', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_dim_market_segment_id'), 'dim_market_segment', ['id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_dim_market_segment_id'), table_name='dim_market_segment')
    op.drop_index(op.f('ix_dim_market_segment_canonical_key'), table_name='dim_market_segment')
    op.drop_table('dim_market_segment')
    op.drop_index(op.f('ix_dim_variant_sku'), table_name='dim_variant')
    op.drop_index(op.f('ix_dim_variant_id'), table_name='dim_variant')
    op.drop_index(op.f('ix_dim_variant_canonical_id'), table_name='dim_variant')
    op.drop_table('dim_variant')
    op.drop_index(op.f('ix_dim_product_slug'), table_name='dim_product')
    op.drop_index(op.f('ix_dim_product_id'), table_name='dim_product')
    op.drop_table('dim_product')
    op.drop_index(op.f('ix_dim_product_family_id'), table_name='dim_product_family')
    op.drop_table('dim_product_family')
    op.drop_index(op.f('ix_dim_source_id'), table_name='dim_source')
    op.drop_index(op.f('ix_dim_source_code'), table_name='dim_source')
    op.drop_table('dim_source')
    op.drop_index(op.f('ix_dim_condition_id'), table_name='dim_condition')
    op.drop_index(op.f('ix_dim_condition_code'), table_name='dim_condition')
    op.drop_table('dim_condition')
    op.drop_index(op.f('ix_dim_category_id'), table_name='dim_category')
    op.drop_index(op.f('ix_dim_category_code'), table_name='dim_category')
    op.drop_table('dim_category')
    op.drop_index(op.f('ix_dim_brand_id'), table_name='dim_brand')
    op.drop_index(op.f('ix_dim_brand_code'), table_name='dim_brand')
    op.drop_table('dim_brand')
    # ### end Alembic commands ###
